// ALL portfolio content lives here (spec §4). Placeholder text starts with "[Placeholder]" so it is
// easy to find and replace. Item `order` runs bottom → top on each wall (oldest first for dated
// items). Each section needs 3–8 items.

import type { Item, Portfolio, Profile, Section } from './types';

export const profile: Profile = {
  name: 'Your Name',
  title: 'Developer Portfolio',
  summary:
    '[Placeholder] Software developer who likes building fast, playful interfaces and the systems behind them. Climber on weekends.',
  location: '[Placeholder] City, Country',
  email: 'you@example.com',
  links: [
    { label: 'GitHub', url: 'https://github.com/' },
    { label: 'LinkedIn', url: 'https://www.linkedin.com/' },
  ],
  // resumeUrl: '/resume.pdf',
};

export const sections: Section[] = [
  {
    id: 'projects',
    label: 'Projects',
    navLabel: 'Projects',
    order: 0,
    intro: '[Placeholder] Things I have built end to end.',
  },
  {
    id: 'experience',
    label: 'Experience',
    navLabel: 'Experience',
    order: 1,
    intro: '[Placeholder] Where I have worked and studied.',
  },
  {
    id: 'skills',
    label: 'Skills',
    navLabel: 'Skills',
    order: 2,
    intro: '[Placeholder] Languages, frameworks and tools I use.',
  },
  {
    id: 'about',
    label: 'About & Contact',
    navLabel: 'About',
    order: 3,
    intro: '[Placeholder] Who I am and how to reach me.',
  },
];

export const items: Item[] = [
  // Projects (oldest at the bottom of the board)
  {
    id: 'project-a',
    section: 'projects',
    order: 0,
    tag: 'Project A',
    kind: 'project',
    name: 'Project A',
    dates: { start: '2023-02', end: '2023-05' },
    summary: '[Placeholder] One-line description of what this project does.',
    description:
      '[Placeholder] What it does, who it is for and why you built it. Mention the hardest problem you solved.\n\n[Placeholder] A second paragraph about results or what you learned.',
    tech: ['Python', 'FastAPI', 'PostgreSQL'],
    highlights: ['[Placeholder] A feature or result worth calling out', '[Placeholder] A number that shows impact'],
    links: { github: 'https://github.com/' },
  },
  {
    id: 'project-b',
    section: 'projects',
    order: 1,
    tag: 'Project B',
    kind: 'project',
    name: 'Project B',
    dates: { start: '2023-09', end: '2024-01' },
    summary: '[Placeholder] One-line description of what this project does.',
    description: '[Placeholder] Short write-up of the project.',
    tech: ['TypeScript', 'React', 'Node.js'],
    highlights: ['[Placeholder] Highlight'],
    links: { github: 'https://github.com/', demo: 'https://example.com/' },
  },
  {
    id: 'project-c',
    section: 'projects',
    order: 2,
    tag: 'Project C',
    kind: 'project',
    name: 'Project C',
    dates: { start: '2024-03', end: '2024-06' },
    summary: '[Placeholder] One-line description of what this project does.',
    description: '[Placeholder] Short write-up of the project.',
    tech: ['Java', 'Android'],
    links: { github: 'https://github.com/' },
  },
  {
    id: 'project-d',
    section: 'projects',
    order: 3,
    tag: 'Project D',
    kind: 'project',
    name: 'Project D',
    dates: { start: '2024-09', end: '2025-02' },
    summary: '[Placeholder] One-line description of what this project does.',
    description: '[Placeholder] Short write-up of the project.',
    tech: ['PyTorch', 'C++', 'CUDA'],
    highlights: ['[Placeholder] Highlight', '[Placeholder] Another highlight'],
    links: { github: 'https://github.com/' },
  },
  {
    id: 'project-e',
    section: 'projects',
    order: 4,
    tag: 'Project E',
    kind: 'project',
    name: 'Project E',
    dates: { start: '2025-06' },
    summary: '[Placeholder] One-line description of what this project does.',
    description: '[Placeholder] Short write-up of the project.',
    tech: ['Three.js', 'TypeScript', 'Astro'],
    links: { github: 'https://github.com/', demo: 'https://example.com/' },
  },

  // Experience (oldest at the bottom of the ice face)
  {
    id: 'university',
    section: 'experience',
    order: 0,
    tag: 'University',
    kind: 'experience',
    company: '[Placeholder] University Name',
    role: 'B.S. Computer Science',
    dates: { start: '2021-09', end: '2025-05' },
    location: '[Placeholder] City',
    summary: '[Placeholder] Focus areas, GPA if you want it here, relevant coursework.',
    bullets: ['[Placeholder] Relevant coursework', '[Placeholder] Clubs, awards or research'],
  },
  {
    id: 'company-a',
    section: 'experience',
    order: 1,
    tag: 'Company A',
    kind: 'experience',
    company: '[Placeholder] Company A',
    role: 'Software Engineering Intern',
    dates: { start: '2024-06', end: '2024-08' },
    location: '[Placeholder] City',
    summary: '[Placeholder] What the team does.',
    bullets: ['[Placeholder] What you shipped', '[Placeholder] Impact in numbers'],
    tech: ['Go', 'Kubernetes'],
  },
  {
    id: 'company-b',
    section: 'experience',
    order: 2,
    tag: 'Company B',
    kind: 'experience',
    company: '[Placeholder] Company B',
    role: 'Software Engineer',
    dates: { start: '2025-07' },
    location: '[Placeholder] City',
    summary: '[Placeholder] What the team does.',
    bullets: ['[Placeholder] Scope of your role', '[Placeholder] Something you owned end to end'],
    tech: ['TypeScript', 'AWS'],
  },

  // Skills (one hold per group)
  {
    id: 'languages',
    section: 'skills',
    order: 0,
    tag: 'Languages',
    kind: 'skills',
    name: 'Languages',
    skills: [
      { name: 'TypeScript', level: 'expert' },
      { name: 'Python', level: 'expert' },
      { name: 'Java', level: 'proficient' },
      { name: 'C++', level: 'familiar' },
    ],
  },
  {
    id: 'frameworks',
    section: 'skills',
    order: 1,
    tag: 'Frameworks',
    kind: 'skills',
    name: 'Frameworks',
    skills: [
      { name: 'React', level: 'expert' },
      { name: 'Three.js', level: 'proficient' },
      { name: 'FastAPI', level: 'proficient' },
      { name: 'Node.js', level: 'proficient' },
    ],
  },
  {
    id: 'ml-data',
    section: 'skills',
    order: 2,
    tag: 'ML & Data',
    kind: 'skills',
    name: 'ML & Data',
    skills: [
      { name: 'PyTorch', level: 'proficient' },
      { name: 'NumPy / pandas', level: 'proficient' },
      { name: 'SQL', level: 'proficient' },
    ],
    note: '[Placeholder] Optional note about this group.',
  },
  {
    id: 'tools',
    section: 'skills',
    order: 3,
    tag: 'Tools',
    kind: 'skills',
    name: 'Tools',
    skills: [
      { name: 'Git', level: 'expert' },
      { name: 'Docker', level: 'proficient' },
      { name: 'AWS', level: 'familiar' },
      { name: 'Linux', level: 'proficient' },
    ],
  },

  // About & Contact
  {
    id: 'who-i-am',
    section: 'about',
    order: 0,
    tag: 'Who I am',
    kind: 'about',
    heading: 'Who I am',
    body: '[Placeholder] A couple of sentences about who you are, what you like building and what you are looking for next.',
  },
  {
    id: 'off-the-keyboard',
    section: 'about',
    order: 1,
    tag: 'Off the keyboard',
    kind: 'about',
    heading: 'Off the keyboard',
    body: '[Placeholder] A short personal note about climbing and why this site is an island of climbing walls.',
  },
  {
    id: 'get-in-touch',
    section: 'about',
    order: 2,
    tag: 'Get in touch',
    kind: 'contact',
    heading: 'Get in touch',
  },
];

export const portfolio: Portfolio = { profile, sections, items };
